FROM node:20-bookworm-slim AS builder

WORKDIR /app/client

COPY client/package*.json ./
RUN npm ci

COPY client/ ./

RUN npm run build

FROM caddy:2.8-alpine

COPY client/Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /app/client/dist /srv
