// This file re-exports from the media/ module directory for backward compatibility.
// New code should import from "./media" or "./media/index" directly.

export type {
  AudioDeviceInventory,
  AudioDeviceOption,
  CameraActionResult,
  CameraDeviceOption,
  CameraStateSnapshot,
  RemoteVideoTile,
  RoutingMode,
  ScreenShareStartOptions,
  ScreenShareStateSnapshot,
  TransportHealthState,
} from "./media/index";

export {
  cleanupMediaTransports,
  initializeMediaTransports,
  isSpeakerSelectionSupported,
  listAudioDevices,
  listCameraDevices,
  localCameraEnabled,
  localCameraError,
  localCameraStream,
  localScreenShareEnabled,
  localScreenShareError,
  localScreenShareStream,
  remoteVideoTiles,
  resetPreferredAudioDevices,
  setMicrophoneMuted,
  setPreferredCameraDevice,
  setPreferredMicrophoneDevice,
  setPreferredSpeakerDevice,
  setSpeakersMuted,
  startLocalCameraProducer,
  startLocalScreenProducer,
  stopLocalCameraProducer,
  stopLocalScreenProducer,
  subscribeCameraState,
  subscribeAudioPlaybackError,
  subscribeScreenState,
  subscribeTransportHealth,
  subscribeVideoTiles,
} from "./media/index";
